# Generated by Django 5.0.2 on 2025-01-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_manage_hr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='requires_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
