# Generated by Django 5.0.2 on 2025-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_employee_can_manage_hr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='can_manage_hr',
            new_name='can_hire_hr',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='requires_password_change',
        ),
        migrations.AddField(
            model_name='employee',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
