# Generated by Django 5.0.2 on 2025-01-10 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_remove_employee_can_hire_hr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_password_reset_required',
        ),
    ]
